// services/pdf.service.js
// PDF generation service for SMB business reports
//
// Converts analytics + charts into a professional PDF
// No UI, no dashboard, no frontend required

const fs = require("fs");
const path = require("path");
const puppeteer = require("puppeteer");

// -------------------------------
// Helpers
// -------------------------------
function ensureDir(dirPath) {
  if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath, { recursive: true });
  }
}

function formatDate(ts) {
  return new Date(ts).toLocaleDateString();
}

// -------------------------------
// HTML template builder
// -------------------------------
function buildHtmlReport({ site, analytics, charts }) {
  const summary = analytics.summary;

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>AI Support Report</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      color: #111;
      margin: 40px;
    }
    h1, h2, h3 {
      color: #4F46E5;
    }
    .section {
      margin-bottom: 40px;
    }
    .metric {
      display: inline-block;
      margin-right: 30px;
      font-size: 16px;
    }
    .metric b {
      font-size: 22px;
      display: block;
    }
    img {
      max-width: 100%;
      margin-top: 20px;
      border: 1px solid #eee;
      padding: 10px;
      background: #fff;
    }
    .footer {
      margin-top: 60px;
      font-size: 12px;
      color: #777;
      text-align: center;
    }
  </style>
</head>

<body>

  <h1>AI Support Performance Report</h1>
  <p><b>Business:</b> ${site.domain}</p>
  <p><b>Period:</b> ${analytics.meta.period}</p>
  <p><b>Report Range:</b> ${formatDate(analytics.meta.from)} – ${formatDate(analytics.meta.to)}</p>

  <div class="section">
    <h2>Executive Summary</h2>

    <div class="metric">
      <b>${summary.totalConversations}</b>
      Total Conversations
    </div>

    <div class="metric">
      <b>${summary.aiResolutionRate}%</b>
      AI Resolution Rate
    </div>

    <div class="metric">
      <b>${summary.escalated}</b>
      Escalated to Owner
    </div>

    <div class="metric">
      <b>${summary.estimatedHoursSaved}</b>
      Estimated Hours Saved
    </div>

    <p style="margin-top:20px;">
      Your AI assistant handled <b>${summary.aiHandled}</b> customer conversations automatically,
      significantly reducing manual workload and response time.
    </p>
  </div>

  <div class="section">
    <h2>AI vs Owner Involvement</h2>
    <img src="file://${charts.aiVsEscalation}" />
  </div>

  <div class="section">
    <h2>Customer Conversations by Channel</h2>
    <img src="file://${charts.channels}" />
  </div>

  <div class="section">
    <h2>Top Customer Issues</h2>
    <img src="file://${charts.intents}" />
  </div>

  <div class="section">
    <h2>Customer Activity (Peak Hours)</h2>
    <img src="file://${charts.peakHours}" />
  </div>

  <div class="section">
    <h2>Knowledge Improvement Opportunities</h2>
    <p>
      These topics caused escalations and may need better documentation:
    </p>
    <ul>
      ${
        analytics.knowledgeGaps.length
          ? analytics.knowledgeGaps.map(k =>
              `<li><b>${k.topic}</b> – ${k.occurrences} times</li>`
            ).join("")
          : "<li>No major gaps detected 🎉</li>"
      }
    </ul>
  </div>

  <div class="footer">
    Generated by Mascot AI Support • ${new Date().toLocaleString()}
  </div>

</body>
</html>
`;
}

// -------------------------------
// PDF generator
// -------------------------------
async function generatePdfReport({
  site,
  analytics,
  charts,
  outputDir
}) {
  ensureDir(outputDir);

  const fileName = `ai-support-report-${site.domain}-${Date.now()}.pdf`;
  const outputPath = path.join(outputDir, fileName);

  const html = buildHtmlReport({ site, analytics, charts });

  const browser = await puppeteer.launch({
    headless: "new",
    args: ["--no-sandbox", "--disable-setuid-sandbox"]
  });

  try {
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: "networkidle0" });

    await page.pdf({
      path: outputPath,
      format: "A4",
      printBackground: true,
      margin: {
        top: "20mm",
        bottom: "20mm",
        left: "15mm",
        right: "15mm"
      }
    });
  } finally {
    await browser.close();
  }

  return outputPath;
}

// -------------------------------
// Export
// -------------------------------
module.exports = {
  generatePdfReport
};
